* Gem::Docs
This gem contains ~rake~ tasks to facilitate the production of other gems.

Right now, it provides tasks for running all the code blocks in a ~README.org~
file and a task for exporting ~README.org~ to Git-flavored markdown in
~README.md~

** Installation
Install the gem and add to the application's Gemfile by executing:

#+begin_src sh
  bundle add gem_docs
#+end_src

If bundler is not being used to manage dependencies, install the gem by executing:
#+begin_src sh
  gem install gem_docs
#+end_src

** Usage
*** Update Your Rakefile
To use this gem place the following lines in your gem's Rakefile:
#+begin_src ruby
  require "gem_docs"
  GemDocs.install
#+end_src

*** Generate README.md from README.org
Now, you can write the README in Emacs org-mode, using all its features
including the execution of code blocks, and the export to git-flavored
markdown.  Github renders markdown better that it renders org files, so this
helps with the readability of the README on github.

#+begin_src ruby
  rake docs:readme
#+end_src

*** Run the Code Blocks in README.org
You can invoke ~emacsclient~ to run all the examples in you README that are
set for evaluation:

#+begin_src ruby
 rake docs:examples
#+end_src

** Development
After checking out the repo, run `bin/setup` to install dependencies. Then,
run `rake spec` to run the tests. You can also run `bin/console` for an
interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake
install`. To release a new version, update the version number in `version.rb`,
and then run `bundle exec rake release`, which will create a git tag for the
version, push git commits and the created tag, and push the `.gem` file to
[rubygems.org](https://rubygems.org).

** Contributing

Bug reports and pull requests are welcome on GitHub at
https://github.com/ddoherty03/gem-docs.

** License

The gem is available as open source under the terms of the [MIT
License](https://opensource.org/licenses/MIT).
