# frozen_string_literal: true

require 'debug'

module GemDocs
  module Overview
    extend self

    # @return String The overview from README per config
    def write_overview_to_lib
      gem_name = File.basename(Dir.pwd)
      target   = File.join("lib", "#{gem_name}.rb")

      return unless File.exist?(target)

      overview = extract(GemDocs::ORG)
      return unless overview

      binding.break
      old_lib_content = File.read(target)
      old_lib_comment = old_lib_content.match(/\A(#~~+#\n.#~~+#\n)+/m)
      new_lib_comment = <<~RUBY
        #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
        # Gem Overview (auto-generated by gem_docs)
        #
        #{overview.lines.map { |l| "# #{l.rstrip}" }.join("\n")}
        #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
      RUBY

      begin
        # remove old comment banner
        # contents.sub!(/\A(#~+*#\$.*~~#\n)+/m, "")
      rescue
        nil
      end

      File.write(target, new_doc + "\n" + contents)
    end


    # Returns a markdown/Org string containing the overview section
    def extract(readme_path)
      text = File.read(readme_path)

      extract_by_markers(text) || extract_by_headings(text) || nil
    end

    # ----------------------------------------------------------------------

    def extract_by_markers(text)
      start_m, end_m = GemDocs.config.overview_markers
      return unless start_m && end_m
      return unless text.include?(start_m) && text.include?(end_m)

      inner = text[/#{Regexp.escape(start_m)}(.*?)#{Regexp.escape(end_m)}/m, 1]
      return unless inner

      inner.strip
    end

    # ----------------------------------------------------------------------

    def extract_by_headings(text)
      heads = GemDocs.config.overview_headings
      return if heads.nil? || heads.empty?

      result = ''
      heads.each do |h|
        if text =~ /^\*+\s+#{Regexp.escape(h)}\s*$/
          start_idx = Regexp.last_match.begin(0)

          # find next heading
          tail = text[start_idx + 1..-1]
          result =
            if tail =~ /^\*+ /
              end_idx = start_idx + Regexp.last_match.begin(0)
              text[start_idx...end_idx].strip
            else
              tail.strip
            end
        end
      end
      result
    end
  end
end
