# frozen_string_literal: true

require 'strscan'
require 'debug'

module GemDocs
  module Overview
    OVERVIEW_RE = /^\#\s*Gem Overview.*^\#[^\n]*$/m

    # @return String The overview from README per config
    def self.write_overview?
      repo = Repo.from_gemspec
      target = File.join("lib", "#{repo.name}.rb")

      return false unless File.exist?(target)

      overview = extract(GemDocs::ORG)
      return false unless overview

      old_lib = File.read(target)
      has_old_comment = old_lib.match(OVERVIEW_RE)
      old_comment = has_old_comment.to_s

      new_comment = <<~RUBY.chomp
        # Gem Overview (auto-generated by gem_docs)
        #
        #{overview.lines.map { |l| l.match?(/\A\s*\z/) ? '#' : "# #{l.rstrip}" }.join("\n")}
      RUBY
      return false if old_comment == new_comment

      new_lib = ''
      begin
        new_lib =
          if has_old_comment
            # There was an overview in the old_lib_content, so replace it with
            # the new_lib_comment.
            old_lib.sub(old_comment, new_comment)
          else
            # There was no overview in the old_lib_content, so place this at the
            # beginning after any directives such as #frozen_string_literal
            prelim_re = %r<\A(?:
                         (^\s*\n) |
                         (^\#![^\n]*\n) |
                         (^\#\s*-\*-.*-\*-\s*\n) |
                         (^\#\s*[A-Za-z_][A-Za-z0-9_]*\s*[:=]\s*.*\n)
                        )*>x
            scanner = StringScanner.new(old_lib)
            prelims = scanner.scan(prelim_re)
            prelims + new_comment + "\n\n" + scanner.rest
          end
      rescue
        false
      end
      File.write(target, new_lib) > 0
    end

    def self.present?
      repo = Repo.from_gemspec
      target = File.join("lib", "#{repo.name}.rb")

      return false unless File.exist?(target)

      File.read(target).match?(OVERVIEW_RE)
    end

    class << self
      private

      # Returns a markdown/Org string containing the overview section
      def extract(readme_path)
        text = File.read(readme_path)

        extract_by_markers(text) || extract_by_headings(text) || nil
      end

      # ----------------------------------------------------------------------

      def extract_by_markers(text)
        start_m, end_m = GemDocs.config.overview_markers
        return unless start_m && end_m
        return unless text.include?(start_m) && text.include?(end_m)

        inner = text[/#{Regexp.escape(start_m)}(.*?)#{Regexp.escape(end_m)}/m, 1]
        return unless inner

        inner.strip
      end

      # ----------------------------------------------------------------------

      def extract_by_headings(text)
        heads = GemDocs.config.overview_headings
        return if heads.nil? || heads.empty?

        result = ''
        heads.each do |h|
          if text =~ /^\*+\s+#{Regexp.escape(h)}\s*$/
            start_idx = Regexp.last_match.begin(0)

            # find next heading
            tail = text[start_idx + 1..-1]
            result =
              if tail =~ /^\*+ /
                end_idx = start_idx + Regexp.last_match.begin(0)
                text[start_idx...end_idx].strip
              else
                tail.strip
              end
          end
        end
        result
      end
    end
  end
end
