#-------------------------------------------------------------
# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
# 
# Right now, it provides tasks for running all the code blocks in a ~README.org~
# file and a task for exporting ~README.org~ to Git-flavored markdown in
# ~README.md~
#-------------------------------------------------------------


require "rake"
require "rake/dsl_definition"
require "fileutils"

require_relative "gem_docs/version"
require_relative "gem_docs/config"
require_relative "gem_docs/emacs"
require_relative "gem_docs/overview"
require_relative "gem_docs/yard"
require_relative "gem_docs/tasks"

module GemDocs
end
